set number
set relativenumber
syntax enable
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set nowrap
set smartcase
set belloff=all

" change color of highlighting all search
hi Search ctermbg=DarkYellow

" change color in visual mode
hi Visual cterm=none ctermbg=DarkGrey ctermfg=cyan

" redo -> shift+u
nnoremap U <C-r>

" delete into black hole register
nnoremap d "_d
nnoremap D "_D
vnoremap d "_d
vnoremap D "_D

" scroll up and down gt (go-top) and gb (go-bottom)
nmap K 15kzz
vmap K 15kzz
nmap J 15jzz
vmap J 15jzz

" mapping shift space into esc
map <S-Space> <Esc>
imap <S-Space> <Esc>

" yank to clipboard
map <leader>c :set clipboard=unnamed<CR>
map <leader>C :set clipboard=autoselect,exclude:cons\<CR>
